-- markdown_css_sample.lua
-- Shared sample for the markdown CSS display test (dev-only, test/ is
-- excluded from release zips). Pure string concat, no wbuilder dependency:
-- required both by test/markdown_css.lua (runui eyeballing) and by
-- test/test_markdown_css.lua (headless render assertions), so the two never
-- fork. Shapes mirror what AssistantDialog:_createResultText emits after T()
-- substitution (C locale): Question/Thought/Response/Search container divs,
-- a ```reasoning fence closed by `---`, `---` inter-round separators, a
-- `⌗` keyword line for Search, and `#q:` follow-up links. The first block
-- keeps the generic LLM shapes (h1-h6/lists/tables/code/CJK) for CSS
-- eyeballing; the tail is the two-round dialog output under test.
local SAMPLE = table.concat({
    "# The Lord of the Rings\n",
    "\n",
    "## Heading scale (h1/h2 capped, h3-h6 default)\n",
    "\n",
    "# Heading 1\n",
    "## Heading 2\n",
    "### Heading 3\n",
    "#### Heading 4\n",
    "##### Heading 5\n",
    "###### Heading 6\n",
    "\n",
    "# Characters\n",
    "\n",
    "- **Frodo Baggins** — a small, quiet hobbit of the Shire who inherits a plain gold ring that proves to be the One Ring. He volunteers to carry it to Mordor though he has no warrior skill, and his quiet endurance carries the quest further than strength ever could. _<u>bearer of the One Ring</u>_\n",
    "- **Samwise Gamgee** — Frodo's gardener and steadfast companion, whose loyalty never wavers from the Shire to Mount Doom. He carries Frodo, in every sense, through the darkest chapters. _<u>ally of Frodo</u>_\n",
    "  - Travels with a [map of Mordor](https://example.com) inside a list item\n",
    "  - Nested note two\n",
    "    - Deep note about lembas bread\n",
    "    - Deep note about the light of Earendil\n",
    "- **Gandalf** — a wandering wizard of quiet humor and sudden fire, sent to rally the free peoples against Sauron. He falls in Moria and returns changed. _<u>guide and catalyst of the Fellowship</u>_\n",
    "\n",
    "# Locations\n",
    "\n",
    "1. The Shire\n",
    "2. Rivendell\n",
    "   1. The Council of Elrond\n",
    "   2. The Fellowship is formed\n",
    "      1. Nine walkers are chosen\n",
    "      2. The Fellowship departs south\n",
    "3. Mordor\n",
    "\n",
    "## Mixed nesting (markers must follow the inner list type)\n",
    "\n",
    "Bullets holding numbered children (rare, shows discs: known limit):\n",
    "\n",
    "- Bullet parent\n",
    "  1. Numbered child one\n",
    "  2. Numbered child two\n",
    "- Bullet parent two\n",
    "\n",
    "Numbered holding bullet children:\n",
    "\n",
    "1. Numbered parent\n",
    "   - Bullet child one\n",
    "   - Bullet child two\n",
    "2. Numbered parent two\n",
    "\n",
    "# Timeline\n",
    "\n",
    "- **Chapter 1:** Bilbo vanishes from his birthday party and leaves the Ring to Frodo.\n",
    "- **Chapter 2:** Gandalf confirms the Ring's identity and urges Frodo to flee the Shire.\n",
    "- **Chapter 3:** The hobbits reach Rivendell after flight, pursuit, and Strider's aid.\n",
    "\n",
    "### Re-immersion\n",
    "\n",
    "* **Where the action stopped:** the Fellowship rests in Lothlorien after losing Gandalf in Moria.\n",
    "* **Protagonist's current objective:** reach Mordor quietly with the Ring.\n",
    "* **Open conflict or mystery:** what became of Merry and Pippin after the breaking.\n",
    "* **Narrative element in focus:** the slow weight of the Ring on Frodo. (object, place, or symbol)\n",
    "* **Prevailing emotional state/tone:** grief mixed with resolve.\n",
    "* **Outstanding questions:** can the Fellowship hold together without Gandalf.\n",
    "\n",
    "---\n",
    "### 1. Book Information\n",
    "\n",
    "* **Genre**: Fantasy, Adventure\n",
    "* **Publication Date**: 29 July 1954\n",
    "* **Publisher**: Allen and Unwin\n",
    "* **Plot Summary**: A hobbit inherits a magic ring and must destroy it in Mount Doom.\n",
    "\n",
    "---\n",
    "### 2. Historical and Cultural Context\n",
    "\n",
    "> All that is gold does not glitter, not all those who wander are lost.\n",
    ">\n",
    "> > Verse from Bilbo's poem about Aragorn; check nested indent stays sane.\n",
    "> > Second line of the nested quote.\n",
    "\n",
    "---\n",
    "# 3. About the Author\n",
    "\n",
    "J.R.R. Tolkien (1892-1973) was an Oxford professor of Anglo-Saxon with **bold** opinions on myth, *italic* affection for languages, and `inline code` nowhere near his desk. CJK mixed: 托尔金的中土世界构建极为完整，**精灵语**与`年表`混排，用来检查 CJK 字体与换行。\n",
    "\n",
    "# 4. Similar Books Recommendations\n",
    "\n",
    "| Title | Author | Why recommended |\n",
    "| --- | --- | --- |\n",
    "| The Silmarillion | J.R.R. Tolkien | Same world, deeper myths |\n",
    "| The Name of the Wind | Patrick Rothfuss | A gifted outcast tells his own legend |\n",
    "| Lin | Designer | Mixed 中文备注测试 |\n",
    "\n",
    "## Wide table (header nowrap, body wraps)\n",
    "\n",
    "| Component | Description | Status |\n",
    "| --- | --- | --- |\n",
    "| ScrollHtmlWidget | Renders this HTML through MuPDF with VIEWER_CSS | OK |\n",
    "| assistant_mdparser | hoedown C binding if present, else pure Lua fallback | OK |\n",
    "| A very long header label that must stay on one line | Body cells should wrap instead of widening the column forever and ever | Pending review of overflow-wrap behavior |\n",
    "\n",
    "# ★ Core Arguments\n",
    "\n",
    "* The Ring corrupts through **absolute power**, not strength of arms.\n",
    "* Small, *ordinary* courage moves history more than kings and wizards.\n",
    "\n",
    "# ◆ Essential Facts and Conclusions\n",
    "\n",
    "* Published 1954-1955; three volumes, one continuous story.\n",
    "* Central claim: mercy and endurance defeat domination.\n",
    "\n",
    "# ● Core Idea\n",
    "\n",
    "A magic ring must be thrown into a volcano before it enslaves everyone.\n",
    "\n",
    "# ○ Fun Analogy\n",
    "\n",
    "Like carrying a heavy, whispering backpack that tells you to keep it.\n",
    "\n",
    "# 1. Structure and Clauses\n",
    "\n",
    "* **Sentence Type**: Complex\n",
    "* **Analysis**: Main clause carries the quest; subordinate clauses add motive.\n",
    "\n",
    "# 2. Parts of Speech and Tenses\n",
    "\n",
    "* Past tense narration; proper nouns mark peoples and places.\n",
    "\n",
    "1. __reluctant__: unwilling, hesitant : not wanting to do something\n",
    "2. __endurance__: stamina, persistence : the ability to keep going\n",
    "\n",
    "```lua\n",
    "local function hello(name)\n",
    "    -- fenced code should wrap, not overflow\n",
    "    return \"hello, \" .. (name or \"world\")\n",
    "end\n",
    "print(hello(\"koreader\"))\n",
    "```\n",
    "\n",
    "---\n",
    "\n",
    "<div class=\"assistant-label\">☺ Question</div>\n",
    "\n",
    "➤ What is the One Ring?\n",
    "\n",
    "<div class=\"assistant-label assistant-label--thought\">※ Deeply Thought</div>\n",
    "\n",
    "```reasoning\n",
    "The user asks about a classic book, so internal knowledge suffices and no web search is needed. The answer follows the book_info structure with four sections.\n",
    "```\n",
    "\n",
    "---\n",
    "\n",
    "<div class=\"assistant-label\">✦ Response</div>\n",
    "\n",
    "# The Ring and Its Nature\n",
    "\n",
    "The One Ring was forged by Sauron in Mount Doom to rule the other Rings of Power.\n",
    "\n",
    "## Why It Corrupts\n",
    "\n",
    "It amplifies the bearer's desires: power promises to the strong, escape to the fearful.\n",
    "\n",
    "- **Power** - it offers mastery over others.\n",
    "- **Burden** - it grows heavier on the bearer.\n",
    "\n",
    "---\n",
    "\n",
    "<div class=\"assistant-label\">☺ Question</div>\n",
    "\n",
    "➤ Who carries it to Mordor?\n",
    "\n",
    "<div class=\"assistant-label\">✦ Search</div>\n",
    "\n",
    "⌗ Frodo Baggins Ring bearer Mordor\n",
    "\n",
    "<div class=\"assistant-label\">✦ Response</div>\n",
    "\n",
    "Frodo Baggins carries the Ring to Mordor with Samwise Gamgee.\n",
    "\n",
    "Final paragraph with **bold**, *italic* and footnote.[^1]\n",
    "\n",
    "[^1]: Footnote text renders if the parser supports footnotes.\n",
    "\n",
    "##### You may find these topics interesting:\n",
    "\n",
    "- [Who is Tom Bombadil?](#q:Who%20is%20Tom%20Bombadil%3F)\n",
    "- [Why does the Ring corrupt its bearer?](#q:Why%20does%20the%20Ring%20corrupt%20its%20bearer%3F)\n",
}, "")

return SAMPLE
